### ISSUE TITLE
Provide paradata schemas in json-ld/schema.org

### ISSUE THREAD

**Issue by science** [learningtapestry/learningregistry#13]
LR 1.0 paradata is using JSON schemas based on activitystrea.ms. Probably we should provide alternative schemas based on json-ld/schema.org. Activitystrea.ms 2.0 is using JSON-LD: https://www.w3.org/TR/activitystreams-core/ - Probably we just need to provide a specific structure for handling our aggregate data elements.

Reference to LR 1.0 paradata: https://docs.google.com/document/d/19ZkVpxQn1O1dLhCZClkQkzvypziBI7gBytszTxgXmX0/edit?hl=en_US#heading=h.to4n0dgvtvb7

Examples/quick start for LR 1.0 paradata: http://learningregistry.org/wp-content/uploads/2013/06/ParadataTwenty.pdf

**Comment by science** [comment]
From Adam Blum:
- resource access count - aggregated by day (or you choose time period)
- resource usage count (indicates that resource was actually consumed) - aggregated by day
- resource ratings (includes time of rating and identity of rater)
- resource reviews (time of review and identiy of reviewer)

**Comment by science** [comment]
Note: "Resource Ratings" and "Resource Reviews" might be 100% activitystreams format - no adaptation required.. If so, just cite the appropriate format and put it in json-schema

**Comment by science** [comment]
@joehobson suggests that we also need a statement that includes a "second object." Such as:
- NN teachers used resource XYZ as part of lesson ABC

**Comment by joehobson** [comment]
This doc has a variety of examples that may be helpful: https://docs.google.com/document/d/19ZkVpxQn1O1dLhCZClkQkzvypziBI7gBytszTxgXmX0/edit?pref=2&pli=1#heading=h.to4n0dgvtvb7

Some of the statements modeled in that doc include the "second object" that @science mentions above, and sometimes also a "context" for where the activity took place (since you may not want to infer that the activity happened on the platform of the publisher of the paradata).

Examples:
- Resource XYZ was incorporated into **lesson plan** ABC by a teacher.
- Resource XYZ was matched to NN academic content standards on the ABC educator portal by a teacher

See the full doc for many, many more examples.

**Comment by RonDrabkin** [comment]
We had thought to limit it for now.  Perhaps keep it a four elements suggested by Adam+ a comment field that could be used for other context.  Limiting the number of elements would make it easier to get various companies to agree to use it.   But, we would like Steve/Joe/James to make the final decision/spec.

**Comment by adamblum** [comment]
The attributes I mentioned were those that were discussed at DoE GoOpen meeting. Basically concentrating purely on hits/usage/ratings/reviews and not on "compositional usage" (resource is used in some wider context) for now

**Comment by andersoncardoso** [comment]
In case anyone wants to review, the proposed changes to be compliant with activitystreams 2.0 are here https://github.com/learningtapestry/metadataregistry/blob/paradata/docs/paradata.md
and the corresponding json-schema https://github.com/learningtapestry/metadataregistry/blob/paradata/app/schemas/paradata.json.erb

**Comment by andersoncardoso** [comment]
I'm marking this as closed since we have both the spec and a working implementation. But if anyone else thinks we should add/change anything, let me know. tks

**Comment by RonDrabkin** [comment]
I'm getting a 404 on the links from Anderson above (maybe I don't have access?)  But a couple of questions on the spec:
-for the resource consumed count, does it count if say, a video is played for just a couple of seconds?  or does it need to be watched to the end?  If not decided, I'd suggest the event be on hitting play
-note that catalogs have both embedded resources and resources that are linked.  For linked resources there is probably not a way of capturing if they are consumed or not.

**Comment by andersoncardoso** [comment]
Hello @RonDrabkin ,

these links were from a feature-branch I've merged already (that's why the 404s). 
The correct ones are:

https://github.com/learningtapestry/metadataregistry/blob/master/docs/04_paradata.md

https://github.com/learningtapestry/metadataregistry/blob/master/app/schemas/paradata/schema.json.erb
