### ISSUE TITLE
Install Swagger as static, viewable html into project

### ISSUE THREAD

**Issue by science** [learningtapestry/learningregistry#16]

**Comment by aspino** [comment]
@science Swagger documentation is now available at http://lr-staging.learningtapestry.com/swagger/index.html.

Unfortunately I had to manually tweak the auto-generated spec because grape-swagger does not generate model references for the json payload in `DELETE` requests in the same way that it does for `POST`or `PATCH`. 

Since setting a message body in `DELETE` requests is probably a "questionable" practice it's possible that they do it on purpose or simply don't care because it's not very usual. Anyway, perhaps we should also discuss alternatives to passing the delete token metadata without setting a body.

**Comment by science** [comment]
@aspino Thanks - looks good. This is fine for our initial purpose. 

I'd love to see if we can integrate the JWT signing requirements into this spec in some way? Thoughts? (This is not an urgent request)

**Comment by aspino** [comment]
@science Perhaps we can use the general API description at the top? I'm not sure if it allows formatting, but if it does not, then it would be probably better to link to the specific section on the README, the wiki page or whenever these signing requirements reside.

**Comment by science** [comment]
That sounds good - including information about the JWT element seems great. I wonder also if we can customize "resource" datatype to something like "jwt as string" or something? Saying that field is a string is correct but seriously incomplete for a developer! There's not a big rush on this item..

**Comment by aspino** [comment]
Keep in mind that, for the time being, automatic swagger documentation is disabled. https://github.com/learningtapestry/learningregistry/blob/master/app/api/base.rb#L8

**Comment by science** [comment]
@andersoncardoso - Once we get through to the paradata metadata schema, you might be interested to try to fix the but specified in grape swagger for them with a PR.. Let me know if you're interested and we can try to put that into the workstream..

**Comment by leolara** [comment]
@aspino we have moved this repo to https://github.com/CredentialEngine/CredentialRegistry ; all the stuff should be done there
