### ISSUE TITLE
Database seeds are not loaded in the setup script

### ISSUE THREAD

**Issue by aspino** [learningtapestry/learningregistry#36]
It seems like, when executing the bootstrap script (`bin/setup`), seeds are not loaded at all. And manually adding `bin/rake db:seed` to the script didn't work either.

However, executing `bin/rake db:setup` straight from the command-line works fine.

**Comment by andersoncardoso** [comment]
reposting here the comment from the PR, because it has some important info: 

---

I think the issue was mitigated by just changing the setup script to `bash`. For whatever reason now seems to work.

to improve our project for newcommers, I did the following:
- created a VM setup using vagrant (with a full botstrap script)
- added a "setup guide" doc (with the previous installation instructions from readme, plus a couple more infos)
- added a notice about the possible `seed` issue and how to test and solve it.

**A very important thing to notice**: The default db/user/pass on `.env` was changed to reflect the "metadataregistry" rebranding. So if anyone is relying solely on this file to set the user/pass/db they will receive connection errors when trying to run anything. To fix, just add your specific settings on `.env.local`
